// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLj-ac_nf7UhRZTj0i3HrzHLmUCQAsf8',
    appId: '1:723962598173:web:002a63819355159aeec7f4',
    messagingSenderId: '723962598173',
    projectId: 'car-dashboard-mobile',
    authDomain: 'car-dashboard-mobile.firebaseapp.com',
    storageBucket: 'car-dashboard-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACX0_JsFQNIm-HyiB5mLM3uoQSzr_Ce9Q',
    appId: '1:723962598173:android:df77721b09eca5aeeec7f4',
    messagingSenderId: '723962598173',
    projectId: 'car-dashboard-mobile',
    storageBucket: 'car-dashboard-mobile.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVLj-ac_nf7UhRZTj0i3HrzHLmUCQAsf8',
    appId: '1:723962598173:web:ae908188844353cfeec7f4',
    messagingSenderId: '723962598173',
    projectId: 'car-dashboard-mobile',
    authDomain: 'car-dashboard-mobile.firebaseapp.com',
    storageBucket: 'car-dashboard-mobile.firebasestorage.app',
  );
}
